

/**
 * Extract video ID from YouTube URL
 */
export function extractVideoId(urlOrId) {
  const regExp = /^.*(youtu\.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
  const match = urlOrId.match(regExp);
  if (match && match[2].length === 11) {
    return match[2];
  }
  return urlOrId;
}

/**
 * Validate YouTube URL
 */
export function isValidYouTubeUrl(str) {
  if (!str || typeof str !== 'string') return false;
  return /^(https?:\/\/)?(www\.)?(youtube\.com\/(watch\?v=|embed\/|v\/)|youtu\.be\/)[a-zA-Z0-9_-]{11}/.test(str);
}

/**
 * Fetch YouTube transcript
 * @param {string} videoId - 11-character video ID
 * @returns {string} Full transcript text
 */
export async function fetchYouTubeTranscript(videoId) {
  console.log(`[YouTube] Fetching transcript for video ID: ${videoId} via Piped API...`);
  
  const instances = [
    'https://pipedapi.privacy.com.de',
    'https://api.piped.yt',
    'https://pipedapi.smnz.de',
    'https://pipedapi.drgns.space',
    'https://pipedapi.kavin.rocks'
  ];

  let lastError = null;

  for (const baseUrl of instances) {
    try {
      console.log(`[YouTube] Trying Piped instance: ${baseUrl}`);
      const res = await fetch(`${baseUrl}/streams/${videoId}`);
      if (!res.ok) throw new Error(`${baseUrl} returned ${res.status}`);
      
      const data = await res.json();

      if (!data.subtitles || data.subtitles.length === 0) {
        throw new Error(`Transcript is disabled on this video (${videoId})`);
      }

      // Prefer English, fallback to whatever is first
      const track = data.subtitles.find(s => s.code === 'en' && !s.autoGenerated)
                 || data.subtitles.find(s => s.code === 'en' && s.autoGenerated)
                 || data.subtitles.find(s => s.code.startsWith('en'))
                 || data.subtitles[0];

      const subsRes = await fetch(track.url);
      if (!subsRes.ok) throw new Error(`Failed to fetch subtitle content from ${baseUrl}`);
      let fullText = await subsRes.text();

      // Clean up XML/HTML/WebVTT formatting tightly
      fullText = fullText
        .replace(/<[^>]*>/g, ' ')
        .replace(/WEBVTT/g, '')
        .replace(/\d{2}:\d{2}:\d{2}\.\d{3} --> \d{2}:\d{2}:\d{2}\.\d{3}/g, '')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/[\r\n]+/g, ' ')
        .replace(/\s{2,}/g, ' ')
        .trim();

      console.log(`[YouTube] Transcript extracted via ${baseUrl}! Length: ${fullText.length} characters`);
      return fullText;

    } catch (error) {
      console.warn(`[YouTube] Piped instance ${baseUrl} failed:`, error.message);
      lastError = error;
      // If the video actually lacks transcripts, we shouldn't keep trying proxies!
      if (error.message.includes('Transcript is disabled')) {
        throw error; 
      }
      // Otherwise, loop continues to the next proxy
    }
  }

  // If we exhaust all instances without a success
  console.error('[YouTube] All Piped API instances failed. Last error:', lastError?.message);
  throw new Error('All YouTube proxy endpoints failed. Please try again later.');
}

