import { YoutubeTranscript } from 'youtube-transcript/dist/youtube-transcript.esm.js';

/**
 * Extract video ID from YouTube URL
 */
export function extractVideoId(urlOrId) {
  const regExp = /^.*(youtu\.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
  const match = urlOrId.match(regExp);
  if (match && match[2].length === 11) {
    return match[2];
  }
  return urlOrId;
}

/**
 * Validate YouTube URL
 */
export function isValidYouTubeUrl(str) {
  if (!str || typeof str !== 'string') return false;
  return /^(https?:\/\/)?(www\.)?(youtube\.com\/(watch\?v=|embed\/|v\/)|youtu\.be\/)[a-zA-Z0-9_-]{11}/.test(str);
}

/**
 * Fetch transcript using youtube-transcript package (Innertube API)
 */
async function fetchViaInnertubeAPI(videoId) {
  console.log(`[YouTube] Trying Innertube API via youtube-transcript package...`);
  
  let segments;
  try {
    // Try English first
    segments = await YoutubeTranscript.fetchTranscript(videoId, { lang: 'en' });
  } catch (langErr) {
    // If English not available, try any available language
    console.log(`[YouTube] English transcript not available, trying any language...`);
    segments = await YoutubeTranscript.fetchTranscript(videoId);
  }

  if (!segments || segments.length === 0) {
    throw new Error(`No transcript segments returned for video ${videoId}`);
  }

  const fullText = segments
    .map(s => s.text)
    .join(' ')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/<[^>]*>/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim();

  console.log(`[YouTube] Innertube transcript extracted! Length: ${fullText.length} characters`);
  return fullText;
}

/**
 * Fetch transcript using Piped API instances (fallback)
 */
async function fetchViaPipedAPI(videoId) {
  const instances = [
    'https://pipedapi.kavin.rocks',
    'https://api.piped.yt',
    'https://pipedapi.privacy.com.de',
    'https://pipedapi.smnz.de',
    'https://pipedapi.drgns.space',
  ];

  let lastError = null;

  for (const baseUrl of instances) {
    try {
      console.log(`[YouTube] Trying Piped instance: ${baseUrl}`);
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 8000);

      const res = await fetch(`${baseUrl}/streams/${videoId}`, { signal: controller.signal });
      clearTimeout(timeout);

      if (!res.ok) throw new Error(`${baseUrl} returned ${res.status}`);
      const data = await res.json();

      if (!data.subtitles || data.subtitles.length === 0) {
        throw new Error(`Transcript is disabled on this video (${videoId})`);
      }

      const track = data.subtitles.find(s => s.code === 'en' && !s.autoGenerated)
                 || data.subtitles.find(s => s.code === 'en' && s.autoGenerated)
                 || data.subtitles.find(s => s.code.startsWith('en'))
                 || data.subtitles[0];

      const subsRes = await fetch(track.url);
      if (!subsRes.ok) throw new Error(`Failed to fetch subtitle content from ${baseUrl}`);
      let fullText = await subsRes.text();

      fullText = fullText
        .replace(/<[^>]*>/g, ' ')
        .replace(/WEBVTT/g, '')
        .replace(/\d{2}:\d{2}:\d{2}\.\d{3} --> \d{2}:\d{2}:\d{2}\.\d{3}/g, '')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/[\r\n]+/g, ' ')
        .replace(/\s{2,}/g, ' ')
        .trim();

      console.log(`[YouTube] Piped transcript extracted via ${baseUrl}! Length: ${fullText.length} characters`);
      return fullText;

    } catch (error) {
      console.warn(`[YouTube] Piped instance ${baseUrl} failed:`, error.message);
      lastError = error;
      if (error.message.includes('Transcript is disabled')) throw error;
    }
  }

  throw new Error(`All Piped instances failed. Last: ${lastError?.message}`);
}

/**
 * Fetch YouTube transcript with multi-strategy fallback
 * Strategy 1: Innertube API (direct, via youtube-transcript package)
 * Strategy 2: Piped API instances (proxy fallback)
 *
 * @param {string} videoId - 11-character video ID
 * @returns {string} Full transcript text
 */
export async function fetchYouTubeTranscript(videoId) {
  console.log(`[YouTube] Fetching transcript for video ID: ${videoId}`);

  // Strategy 1: Innertube API (most reliable from serverless)
  try {
    return await fetchViaInnertubeAPI(videoId);
  } catch (err) {
    console.warn(`[YouTube] Innertube API failed: ${err.message}`);
  }

  // Strategy 2: Piped API fallback
  try {
    return await fetchViaPipedAPI(videoId);
  } catch (err) {
    console.warn(`[YouTube] Piped API fallback failed: ${err.message}`);
  }

  throw new Error('Failed to extract YouTube transcript. The video may not have captions enabled, or all extraction methods are currently unavailable.');
}

